### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by CoFix** [BitsumFoundation/bitsum_core#2]
In file included from /home/bitsum/bitsum_core/src/platform/DB.hpp:7:0,
                 from /home/bitsum/bitsum_core/src/Core/BlockChain.hpp:10,
                 from /home/bitsum/bitsum_core/src/Core/BlockChainFileFormat.hpp:11,
                 from /home/bitsum/bitsum_core/src/Core/Node.hpp:11,
                 from /home/bitsum/bitsum_core/src/bitsum/bitsum.cpp:3:
/home/bitsum/bitsum_core/src/platform/DBsqlite3.hpp:6:21: fatal error: sqlite3.h: No such file or directory
compilation terminated.

How can i fix it?

**Comment by i4egod** [comment]
Download amalgamated SQLite 3 and unpack it into bitsum/sqlite folder (source files are referenced via relative paths, so you do not need to separately build it).

https://www.sqlite.org/download.html
